image:
  repository: ghcr.io/piscoaq/editor
  tag: main
  pullPolicy: Always

httpRoute:
  enabled: false

env:
  - name: BACK_URL
    value: https://piscoaq-backend.polyglot-edu.com

service:
  port: 3000

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
