image:
  repository: ghcr.io/piscoaq/editor
  tag: main
  pullPolicy: Always

httpRoute:
  enabled: false

env:
  - name: BACK_URL
    value: https://piscoaq-backend.polyglot-edu.com

service:
  port: 3000

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  httpGet:
    path: /flows
    port: http
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 5
  httpGet:
    path: /flows
    port: http
